# Generated by Django 4.2.3 on 2023-07-26 21:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/def_prof_pic.jpg', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
