# Generated by Django 4.2.3 on 2023-07-26 21:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=accounts.models.default_place_pics, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
