version: "3.9"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
